- name: "Create SFA Enduro worker shared folder"
  become: yes
  file:
    path: "{{ sfa_enduro_worker_preprocessing_shared_path }}"
    owner: "{{ sfa_enduro_worker_system_user }}"
    group: "{{ sfa_enduro_worker_system_group }}"
    mode: 0755
    state: "directory"

- name: Stop and disable legacy preprocessing worker service
  systemd:
    name: preprocessing-worker
    enabled: false
    state: stopped
  failed_when: false

- name: Remove legacy preprocessing worker systemd and config files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/preprocessing-worker.service
    - /etc/systemd/system/preprocessing-worker.service.d
    - /etc/preprocessing-worker.toml
    - /etc/rsyslog.d/50-preprocessing-worker.conf
    - /etc/logrotate.d/preprocessing-worker

- name: Create SFA Enduro worker systemd file
  template:
    src: templates/sfa-enduro-worker.service.j2
    dest: /etc/systemd/system/sfa-enduro-worker.service
    owner: root
    group: root
    mode: 0644
  notify: restart sfa-enduro-worker

- name: Copy the allowed file formats CSV file
  template:
    src: "{{ item }}"
    dest: /etc/allowed_file_formats.csv
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - templates/{{ inventory_hostname }}/allowed_file_formats.csv.j2
    - templates/allowed_file_formats.csv.j2

- name: Copy the SFA Enduro worker config file
  template:
    src: "{{ sfa_enduro_worker_config_file }}"
    dest: /etc/sfa-enduro-worker.toml
    owner: root
    group: root
    mode: 0644
  when: not sfa_enduro_worker_systemd_credentials|bool
  notify: restart sfa-enduro-worker

- name: Use systemd credentials
  block:
    - include_tasks: systemd-creds.yml
      vars:
        service: "sfa-enduro-worker"
        secret_name: "sfa-enduro-worker.toml"
        secret_file: "{{ sfa_enduro_worker_config_file }}"

    - name: "Remove cleartext configuration file"
      file:
        path: "/etc/sfa-enduro-worker.toml"
        state: absent
  when: sfa_enduro_worker_systemd_credentials|bool

- name: Configure SFA Enduro worker logging
  block:
    - include_tasks: configure-logging.yml
      vars:
        service: "sfa-enduro-worker"
        conf_files_name: "sfa-enduro-worker"
        logfile: "{{ sfa_enduro_worker_log_file }}"
        rsyslog_order: "50"
  when: sfa_enduro_worker_use_syslog|bool
