---
# Both services

- name: "Assert usage of systemd as an init system"
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"
  tags:
    - sfa_enduro_worker_install
    - sfa_enduro_worker_configure
    - sfa_dips_install
    - sfa_dips_configure

- import_tasks: create-system-user.yml
  when:
    - sfa_enduro_worker_create_system_user|bool
    - sfa_enduro_worker_install_rpm|bool or sfa_enduro_worker_configure|bool or sfa_dips_install_rpm|bool or sfa_dips_configure|bool
  become: true
  tags:
    - sfa_enduro_worker_install
    - sfa_enduro_worker_configure
    - sfa_dips_install
    - sfa_dips_configure

- name: Install XML validation dependency
  yum:
    name: libxml2
    state: present
  when: sfa_enduro_worker_install_rpm|bool or sfa_dips_install_rpm|bool
  become: true
  tags:
    - sfa_enduro_worker_install
    - sfa_dips_install

# SFA Enduro worker

- import_tasks: install-sfa-enduro-worker.yml
  when: sfa_enduro_worker_install_rpm|bool
  become: true
  tags:
    - sfa_enduro_worker_install

- import_tasks: configure-sfa-enduro-worker.yml
  when: sfa_enduro_worker_configure|bool
  become: true
  tags:
    - sfa_enduro_worker_configure

- name: Ensure sfa-enduro-worker is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: "sfa-enduro-worker"
    enabled: true
    state: "restarted"
  when: sfa_enduro_worker_configure|bool
  tags:
    - sfa_enduro_worker_configure

# SFA DIPs

- import_tasks: install-sfa-dips.yml
  when: sfa_dips_install_rpm|bool
  become: true
  tags:
    - sfa_dips_install

- import_tasks: configure-sfa-dips.yml
  when: sfa_dips_configure|bool
  become: true
  tags:
    - sfa_dips_configure

- name: Ensure sfa-dips is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: "sfa-dips"
    enabled: true
    state: "restarted"
  when: sfa_dips_configure|bool
  tags:
    - sfa_dips_configure
