---
- name: "Assert usage of systemd as an init system"
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"
  tags:
    - sfa_enduro_worker_install
    - sfa_enduro_worker_configure

- import_tasks: create-system-user.yml
  when:
    - sfa_enduro_worker_create_system_user|bool
    - sfa_enduro_worker_install_rpm|bool or sfa_enduro_worker_configure|bool
  become: true
  tags:
    - sfa_enduro_worker_install
    - sfa_enduro_worker_configure

- import_tasks: install-sfa-enduro-worker.yml
  when: sfa_enduro_worker_install_rpm|bool
  become: true
  tags:
    - sfa_enduro_worker_install

- import_tasks: configure-sfa-enduro-worker.yml
  when: sfa_enduro_worker_configure|bool
  become: true
  tags:
    - sfa_enduro_worker_configure

- name: Ensure sfa-enduro-worker is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: "restarted"
  with_items:
    - preprocessing-worker
  when: sfa_enduro_worker_configure|bool
  tags:
    - sfa_enduro_worker_configure
